### ISSUE TITLE
Add uninstall.sh script

### ISSUE THREAD

**Issue by spignelon** [AnswerDotAI/fastsetup#38]
Like the issue #34  mentioned in December of last year,

The fastsetup `./setup-conda.sh` does permanent changes to the current shell's config files or .bashrc; activating the environment as soon as the shell or the terminal starts. Many of us use linux as our daily driver and don't want this. I think it would be better to add an uninstall.sh script since there's none for those who want to uninstall it, and instead of activating the environment as soon as the shell starts by default, what could be done instead is create a function; and those who want to activate will just have to type that command in their terminal and it will activate the conda environment, and an exit command to exit out of the environment.

**Comment by arildnor** [comment]
I am sorry I even started looking at this site (after listening to lesson 2). It basically messed up my environments. I have been trying hard to isolate every "task" in different environments. Never do anything major in (base). This procedure ruined that unfortunately. I was sure it would set up everything  in isolation. But my (base) is now polluted. Running Linux Mint.
An uninstall would help.

**Comment by jph00** [comment]
To remove it just edit your .bashrc to remove the added lines.
